name: Qase tests

on:
  repository_dispatch:     # слушаем внешние вызовы
    types: [qase-run]      # имя события (должно совпадать с тем, что указано в Qase)

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pytest --qase
